[advisories]

ignore = [
		# no fix available
		"RUSTSEC-2023-0071",
		# this one we should actually fix
		"RUSTSEC-2024-0363",
]

[sources]
allow-git = [
		"https://github.com/serenity-rs/serenity?tag=v0.12.1"
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
