//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::{
	blacklist::Entity as Blacklist,
	message_cache::Entity as MessageCache,
	rate_limit::Entity as RateLimit,
	user::Entity as User,
};
